API_BASE_URL = "https://api.tihlde.org"
API_LOGIN_URL = f"{API_BASE_URL}/auth/login/"
API_USER_DATA_URL = f"{API_BASE_URL}/users/me/"
API_EVENTS_URL = f"{API_BASE_URL}/events/?=&expired=false&activity=false&page=1"
API_EVENT_DETAILS_URL = f"{API_BASE_URL}/events/"